# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
#  - name: News
#    url: post
#    weight: 20
  - name: Research Focus
    weight: 20
    hasChildren: true
  - parent: Research Focus
    name: Depth Estimation
    url: depth
  - parent: Research Focus
    name: Occupancy
    url: occ
  - parent: Research Focus
    name: Integrated Sensing and Computing
    url: integrated
  - parent: Research Focus
    name: 3D Surround View
    url: surround
#  - name: People
#    url: people
#    weight: 30
#  - name: Events
#    url: event
#    weight: 40
#  - name: Publications
#    url: publication
#    weight: 50
  - name: Contact
    url: contact
    weight: 60
  - name: VAIS Lab
    url: https://nju-ee.github.io/
    weight: 70
